apiVersion: v1
kind: Service
metadata:
  name: django-app-service
spec:
  type: LoadBalancer
  selector:
    app: django-app-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4444
      nodePort: 30000