# Generated by Django 4.0.6 on 2022-08-18 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nippo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyreportmodel',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeemodel',
            name='user',
        ),
    ]
